### PR TITLE
Create PKGBUILD.append for Tradingview

### PR DESCRIPTION
**Pull request by alexjp**
Doing interference to update package to latest version

### CODE REVIEW

**Review by dr460nf1r3 — COMMENTED** [review]
Before updating the package via interfere, we definitely should give the maintainer appropriate time to update the package after it being flagged out of date. It wasn't flagged yet, so I went ahead and did it: 
image

Lets wait for it it to be updated, and proceed by updating if it doesn't happen soon.

**Comment by alexjp** [comment]
right!! 2 or 3 weeks should be enough ?

**Comment by dr460nf1r3** [comment]
> right!! 2 or 3 weeks should be enough ?

I'd agree! :yum:

**Comment by xiota** [comment]
This package would be a good candidate for autoupdate treatment.  I propose the idea in [comment](https://aur.archlinux.org/packages/tradingview#comment-931060).

May be doable in an interfere.

This is the command to get the current download link and version info: `curl -H 'Snap-Device-Series: 16' http://api.snapcraft.io/v2/snaps/info/tradingview`

**Comment by xiota** [comment]
No longer needed because now using custom pkgbuild: [chaotic-aur/pkgbuild-tradingview](https://github.com/chaotic-aur/pkgbuild-tradingview)

**Pull request closed without merging**
