### PR TITLE
Drop interferes associated with kde-git

### PR DESCRIPTION
**Pull request by xiota**
No longer needed since we're starting from scratch?

Will need to update https://github.com/chaotic-aur/graveyard/issues/373

### CODE REVIEW

**Review by dr460nf1r3 — COMMENTED** [review]
Well, the new builder still uses the same interfere, but the packages are going to be derived from Arch ones afaik. @alexjp decision :)

**Comment by alexjp** [comment]
> Well, the new builder still uses the same interfere, but the packages are going to be derived from Arch ones afaik. @alexjp decision :)

I actually can't make that decision because there is @IslandC0der code in there and I didn't start the kde-git in chaotic :)

For me, I see no issue, but please notice that I am not the author of all those files!

**Comment by xiota** [comment]
I'll go ahead and merge this "soon" since @IslandC0der hasn't responded and progress on the kde-git repo seems to be proceeding as expected.

**Comment by IslandC0der** [comment]
Sorry for the delay!

**Pull request merged**
