### PR TITLE
Fix ark-git pkgver function to standard

### PR DESCRIPTION
**Pull request by alexjp**
copy from konsole-git pkgver

### CODE REVIEW

**Comment by dr460nf1r3** [comment]
LGTM! I'm sure you tested the change? :P

**Comment by alexjp** [comment]
yeah, tested it locally.

it creates a package like this:

 ╰─λ pacman -Qs ark-git
local/ark-git 22.03.70_r4682.g519d8587-1 (kde-applications-git kde-utilities-git)
    Archiving Tool


as opposed to: ark-git 22.03.70.r4682-1

**Review by dr460nf1r3 — APPROVED** [review]

**Comment by dr460nf1r3** [comment]
Very cool, thanks :)

**Comment by PedroHLC** [comment]
One small suggestion: Replace that `_` with a `.`, to match the git-describe behavior. It's important as some tools might want to parse them expecting the format suggested in ArchWiki: https://wiki.archlinux.org/title/VCS_package_guidelines#The_pkgver()_function

**Comment by dr460nf1r3** [comment]
The "_" is present in all of our packages maintained by @IslandC0der though, he was just applying the convention here 👀

**Comment by PedroHLC** [comment]
:sweat_smile:  So @IslandC0der started a wrong trend

**Pull request merged**
