### PR TITLE
Proper fix for sip and kde incompatibility

### PR DESCRIPTION
**Pull request by alexjp**
Proper fix for sip incompatibilities, making the previous one obsolete.

### CODE REVIEW

**Comment by dr460nf1r3** [comment]
Looks good! We should make sure to add the changes to our PKGBUILDs though, if we control the package 👀

**Comment by alexjp** [comment]
Can it go in like this, so that to confirm that later chaotic-aur can produce a whole build of kde-git?

I can then check one by one and fix moving into pkgbuild-xxxx if we own it.

**Comment by dr460nf1r3** [comment]
Sure, we could do this. Its also easy to revert in case its not :) @IslandC0der agree ?

**Review by dr460nf1r3 — APPROVED** [review]

**Review by IslandC0der — APPROVED** [review]
Yeah, looking good! :)

**Pull request merged**
